# Generated by Django 3.2.7 on 2022-01-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled'), ('accepted', 'accepted'), ('finished', 'finished')], default='created', max_length=35),
        ),
    ]
