# Generated by Django 3.2.7 on 2022-01-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
